

#region BUTTON SETTINGS
BACKGROUND_COLOR = f"#f0f0f0"
BACKGROUND_TOP_COLOR_BORDERS = f"#B7808A"
BACKGROUND_BOTTOM_COLOR_BORDERS = f"#B7808A"
BACKGROUND_COLOR_BUTTON = f"#092077"
BACKGROUND_LIGHT_COLOR_BUTTON = f"#62A0FB"
BACKGROUND_BORDER_COLOR = f"#935162"
CHECKBOX_COLOR = f"#8BC431"


BUTTON_HOVER_COLOR_BORDERS = f"#00145c"
#endregion /BUTTON SETTINGS

CONTAINER_HEIGHT = 200
CONTAINER_WIDTH = 220
LARGE_CONTAINER_HEIGHT = 84
LARGE_CONTAINER_WIDTH = 350


#region POSITIONING
CONTAINER_1_X = 39
CONTAINER_1_Y = 65

CONTAINER_2_X = 290
CONTAINER_2_Y = 65

CONTAINER_3_X = 541
CONTAINER_3_Y = 65

BORDER_TOP_X = 0
BORDER_TOP_Y = 0

BORDER_BOT_X = 0
BORDER_BOT_Y = 455


CONTAINER_PORTION_X = 39
CONTAINER_PORTION_Y = 289

CONTAINER_PORTION_NUTRITIONAL_VALUES_X = 411
CONTAINER_PORTION_NUTRITIONAL_VALUES_Y = 289
#endregion /POSITIONING

#region FONTSTYLE
STANDARD_FONTSIZE = 13
TITLE_FONTSIZE = 15
SMALL_FONTSIZE = 10
TEXT_FONT = "Arial"
TEXT_BORDER_COLOR = f"#7A304A"
#endregion /FONTSTYLE

#region MATERIALS
MATERIALS_LIGHT_BORDER = f"#092077"
MATERIALS_STANDARD_BORDER = f"#092077"
CONTAINER_SHADOW_COLOR = f"#092077"
#endregion /MATERIALS






# TOP LEVEL
CONTAINER_SLIDER_POSITION_X = 160
CONTAINER_SLIDER_POSITION_Y = 55

CONTAINER_SLIDER_WIDTH = 480
CONTAINER_SLIDER_HEIGHT = 332



# CONFIG PATH
CONFIG_PATH = f'container_config.ini'