

#region BUTTON SETTINGS
BACKGROUND_COLOR = f"#f0f0f0"
BACKGROUND_COLOR_BORDERS = f"#2c2738"
BACKGROUND_COLOR_BUTTON = f"#0880ae"
BACKGROUND_LIGHT_COLOR_BUTTON = f"#edfaff"

BUTTON_COLOR_BORDERS = f"#423b53"
BUTTON_HOVER_COLOR_BORDERS = f"#685d81"
#endregion /BUTTON SETTINGS

CONTAINER_HEIGHT = 200
CONTAINER_WIDTH = 150
LARGE_CONTAINER_HEIGHT = 125
LARGE_CONTAINER_WIDTH = 350


#region POSITIONING
CONTAINER_1_X = 39
CONTAINER_1_Y = 55

CONTAINER_2_X = 325
CONTAINER_2_Y = 55

CONTAINER_3_X = 611
CONTAINER_3_Y = 55

BORDER_TOP_X = 0
BORDER_TOP_Y = 0

BORDER_BOT_X = 0
BORDER_BOT_Y = 455


CONTAINER_PORTION_X = 39
CONTAINER_PORTION_Y = 270

CONTAINER_PORTION_NUTRITIONAL_VALUES_X = 411
CONTAINER_PORTION_NUTRITIONAL_VALUES_Y = 270
#endregion /POSITIONING

#region FONTSTYLE
STANDARD_FONTSIZE = 13
TITLE_FONTSIZE = 15
SMALL_FONTSIZE = 10
TEXT_FONT = "Arial"
TEXT_BORDER_COLOR = f"#848289"
#endregion /FONTSTYLE

#region MATERIALS
MATERIALS_LIGHT_BORDER = f"#75B1C8"
MATERIALS_STANDARD_BORDER = f"#0880ae"
CONTAINER_SHADOW_COLOR = f"#423b53"
#endregion /MATERIALS






# TOP LEVEL
CONTAINER_SLIDER_POSITION_X = 160
CONTAINER_SLIDER_POSITION_Y = 55

CONTAINER_SLIDER_WIDTH = 480
CONTAINER_SLIDER_HEIGHT = 332



# CONFIG PATH
CONFIG_PATH = f'container_config.ini'