#region MAIN
WINDOW_HEIGHT = 480
WINDOW_WIDTH = 800
#endregion /MAIN

#region BACKGROUND SETTINGS
WINDOW_BG_COLOR = "#f4f8fb"
TOP_BORDER_BG_COLOR = "#2f49cf"
BOTTOM_BORDER_BG_COLOR = "#2f49cf"
BORDER_ACCENTS_BG_COLOR = "#283fbc"
#endregion /BACKGROUND SETTINGS

#region BUTTON SETTINGS
BUTTON_BG_COLOR = "#2f49cf"
BUTTON_HOVER_BG_COLOR = "#18297f"
BUTTON_DISABLED_BG_COLOR = "#18297f"
CHECKBOX_BG_COLOR = "#18297f"
#endregion /BUTTON SETTINGS

#region ADDITIONALLY COLORS
ACCENTS_BG_COLOR = "#092077"
CONTAINER_SHADOW_COLOR = "#ebeff6"
#endregion /ADDITIONALLY COLORS

#region HEIGHT | WIDTH MAIN
CONTAINER_HEIGHT = 200
CONTAINER_WIDTH = 220
LARGE_CONTAINER_HEIGHT = 84
LARGE_CONTAINER_WIDTH = 350
#endregion /HEIGHT | WIDTH MAIN

#region POSITIONING MAIN
CONTAINER_1_X = 22
CONTAINER_1_Y = 65

CONTAINER_2_X = 290
CONTAINER_2_Y = 65

CONTAINER_3_X = 558
CONTAINER_3_Y = 65

BORDER_TOP_X = 0
BORDER_TOP_Y = 0

BORDER_BOT_X = 0
BORDER_BOT_Y = 455

CONTAINER_PORTION_X = 22
CONTAINER_PORTION_Y = 289

CONTAINER_PORTION_NUTRITIONAL_VALUES_X = 427
CONTAINER_PORTION_NUTRITIONAL_VALUES_Y = 289
#endregion /POSITIONING MAIN

#region FONT
STANDARD_FONTSIZE = 13
TITLE_FONTSIZE = 15
SMALL_FONTSIZE = 10
TEXT_FONT = "Arial"
TEXT_BORDER_COLOR = "#a5b8fd"
#endregion /FONT


#region TOPLEVEL SETTINGS
CONTAINER_UI_SETTINGS_WIDTH = 249
CONTAINER_UI_SETTINGS_HEIGHT = 334
#endregion /TOPLEVEL SETTINGS

#region TOPLEVEL UI INPUT
CONTAINER_UI_INPUT_POSITION_X = 50
CONTAINER_UI_INPUT_POSITION_Y = 45

CONTAINER_UI_INPUT_WIDTH = 700
CONTAINER_UI_INPUT_HEIGHT = 342
#endregion /TOPLEVEL UI INPUT




PICTURE_PATH = f'pictures/logo white.PNG'

# CONFIG PATH
CONFIG_PATH = f'config/container_config.ini'
CONFIG_PORTIONS_NAME = f'portionsettings'
LOGSYSTEM_PATH = f'logsystem.csv'

CALCULATION_RATIO = 10 / 3
GRAMM_PER_PORTION = 30

DEBUG = True

#region GPIO PINS
# ultrasonic
GPIO_ULTRASONIC_TR_PIN_C1 = 21
GPIO_ULTRASONIC_TR_PIN_C2 = 26
GPIO_ULTRASONIC_TR_PIN_C3 = 13

GPIO_ULTRASONIC_ECH_PIN_C1 = 20
GPIO_ULTRASONIC_ECH_PIN_C2 = 19
GPIO_ULTRASONIC_ECH_PIN_C3 = 6

# reed
GPIO_REED_PIN_C1 = 23
GPIO_REED_PIN_C2 = 24
GPIO_REED_PIN_C3 = 25

# stepmotor
# GPIO_STEPMOTOR_EN_PIN_C1 = 23
# GPIO_STEPMOTOR_EN_PIN_C2 = 0
# GPIO_STEPMOTOR_EN_PIN_C3 = 0

GPIO_STEPMOTOR_STEP_PIN_C1 = 17 # step pin
GPIO_STEPMOTOR_STEP_PIN_C2 = 27
GPIO_STEPMOTOR_STEP_PIN_C3 = 22

STEPMOTOR_STEPS_REF = 200 # 1 circle
#endregion /GPIO PINS