#region BACKGROUND SETTINGS
BACKGROUND_COLOR = f"#f4f8fb"
BACKGROUND_TOP_COLOR_BORDERS = f"#2f49cf"
BACKGROUND_BOTTOM_COLOR_BORDERS = f"#2f49cf"
BACKGROUND_BORDER_COLOR = f"#283fbc"
#endregion /BACKGROUND SETTINGS

#region BUTTON SETTINGS
BACKGROUND_COLOR_BUTTON = f"#2f49cf"
BUTTON_HOVER_COLOR_BORDERS = f"#18297f"
BACKGROUND_COLOR_DISABLED_BUTTON = f"#18297f"
CHECKBOX_COLOR = f"#18297f"
#endregion /BUTTON SETTINGS

#region HEIGHT | WIDTH
CONTAINER_HEIGHT = 200
CONTAINER_WIDTH = 220
LARGE_CONTAINER_HEIGHT = 84
LARGE_CONTAINER_WIDTH = 350
#endregion /HEIGHT | WIDTH

#region POSITIONING
CONTAINER_1_X = 22
CONTAINER_1_Y = 65

CONTAINER_2_X = 290
CONTAINER_2_Y = 65

CONTAINER_3_X = 558
CONTAINER_3_Y = 65

BORDER_TOP_X = 0
BORDER_TOP_Y = 0

BORDER_BOT_X = 0
BORDER_BOT_Y = 455

CONTAINER_PORTION_X = 22
CONTAINER_PORTION_Y = 289

CONTAINER_PORTION_NUTRITIONAL_VALUES_X = 427
CONTAINER_PORTION_NUTRITIONAL_VALUES_Y = 289
#endregion /POSITIONING

#region FONT
STANDARD_FONTSIZE = 13
TITLE_FONTSIZE = 15
SMALL_FONTSIZE = 10
TEXT_FONT = "Arial"
TEXT_BORDER_COLOR = f"#a5b8fd"
#endregion /FONT

#region MATERIALS
MATERIALS_STANDARD_BORDER = f"#092077"
CONTAINER_SHADOW_COLOR = f"#ebeff6"
#endregion /MATERIALS

#region TOP LEVEL
CONTAINER_SLIDER_POSITION_X = 160
CONTAINER_SLIDER_POSITION_Y = 55

CONTAINER_SLIDER_WIDTH = 480
CONTAINER_SLIDER_HEIGHT = 332
#endregion /TOP LEVEL


PICTURE_PATH = f'pictures/logo white.PNG'

# CONFIG PATH
CONFIG_PATH = f'config/container_config.ini'
CONFIG_PORTIONS_NAME = f'portionsettings'
LOGSYSTEM_PATH = f'logsystem.csv'

CALCULATION_RATIO = 10 / 3
DEBUG = True

